// Catálogo regional de materiais e serviços de marcenaria — fallback estático
// Última revisão de preços: 2026-07-25
// Critério de variação regional: Sul/Sudeste mais caro, Norte/Nordeste mais barato
// Unidades: m² (metro quadrado), un (unidade), par, kit, h (hora)

export type RegionalItem = {
  name: string;
  type: 'material' | 'service';
  unit: string;
  unit_price: number;
};

export const REGIONAL_DEFAULTS: Record<string, RegionalItem[]> = {
  // ── Sudeste ──────────────────────────────────────────────────────────────
  SP: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 92 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 98 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 118 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 85 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 95 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 8 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 32 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 18 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 22 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 28 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 88 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 420 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 95 },
  ],
  RJ: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 90 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 95 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 115 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 83 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 92 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 8 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 30 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 17 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 21 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 27 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 85 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 400 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 92 },
  ],
  MG: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 85 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 90 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 110 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 88 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 7 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 28 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 15 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 19 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 25 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 78 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 380 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 82 },
  ],
  ES: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 83 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 88 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 108 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 76 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 86 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 7 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 27 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 15 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 18 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 24 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 75 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 360 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 80 },
  ],

  // ── Sul ──────────────────────────────────────────────────────────────────
  PR: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 88 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 94 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 112 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 80 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 90 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 8 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 30 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 16 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 20 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 26 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 82 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 390 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 88 },
  ],
  SC: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 87 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 93 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 111 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 79 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 89 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 8 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 29 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 16 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 20 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 25 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 83 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 395 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 89 },
  ],
  RS: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 86 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 92 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 110 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 88 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 7 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 29 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 15 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 19 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 25 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 81 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 385 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 87 },
  ],

  // ── Centro-Oeste ─────────────────────────────────────────────────────────
  GO: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 80 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 86 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 104 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 72 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 82 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 26 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 13 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 17 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 22 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 72 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 340 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 76 },
  ],
  MT: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 84 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 102 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 70 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 80 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 25 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 13 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 16 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 21 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 70 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 330 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 74 },
  ],
  MS: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 79 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 85 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 103 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 71 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 81 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 25 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 13 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 16 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 21 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 71 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 335 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 75 },
  ],
  DF: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 84 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 90 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 108 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 76 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 86 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 7 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 27 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 14 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 18 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 23 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 80 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 375 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 85 },
  ],

  // ── Nordeste ─────────────────────────────────────────────────────────────
  BA: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 76 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 82 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 98 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 68 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 77 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 23 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 12 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 15 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 19 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 65 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 310 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 70 },
  ],
  CE: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 75 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 80 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 97 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 67 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 76 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 22 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 11 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 14 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 18 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 63 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 300 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 68 },
  ],
  PE: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 76 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 81 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 98 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 68 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 77 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 22 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 11 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 14 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 18 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 64 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 305 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 69 },
  ],
  MA: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 73 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 95 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 65 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 74 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 21 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 10 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 13 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 17 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 60 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 285 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 65 },
  ],
  PI: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 72 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 77 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 94 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 64 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 73 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 20 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 10 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 13 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 17 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 60 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 280 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 64 },
  ],
  RN: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 74 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 79 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 96 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 66 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 75 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 21 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 10 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 13 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 17 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 61 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 290 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 66 },
  ],
  PB: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 73 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 95 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 65 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 74 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 21 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 10 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 13 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 17 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 61 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 288 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 65 },
  ],
  AL: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 73 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 95 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 65 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 74 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 21 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 10 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 13 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 17 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 62 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 290 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 66 },
  ],
  SE: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 74 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 79 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 96 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 66 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 75 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 21 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 10 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 13 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 17 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 62 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 292 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 66 },
  ],

  // ── Norte ─────────────────────────────────────────────────────────────────
  AM: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 78 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 84 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 100 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 70 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 79 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 24 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 12 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 15 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 20 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 65 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 310 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 70 },
  ],
  PA: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 77 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 82 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 99 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 69 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 78 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 23 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 11 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 14 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 19 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 63 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 300 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 68 },
  ],
  AC: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 82 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 88 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 105 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 74 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 83 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 25 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 12 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 15 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 20 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 66 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 315 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 71 },
  ],
  RO: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 79 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 85 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 101 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 71 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 80 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 24 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 12 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 15 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 20 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 64 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 305 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 69 },
  ],
  RR: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 83 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 89 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 107 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 75 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 84 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 26 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 12 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 16 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 21 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 67 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 318 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 72 },
  ],
  AP: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 82 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 88 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 105 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 74 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 83 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 6 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 25 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 12 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 15 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 20 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 65 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 312 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 70 },
  ],
  TO: [
    { name: 'MDF 15mm', type: 'material', unit: 'm²', unit_price: 76 },
    { name: 'MDF 18mm', type: 'material', unit: 'm²', unit_price: 81 },
    { name: 'MDF 25mm', type: 'material', unit: 'm²', unit_price: 98 },
    { name: 'Compensado naval', type: 'material', unit: 'm²', unit_price: 68 },
    { name: 'Ferragens kit', type: 'material', unit: 'kit', unit_price: 77 },
    { name: 'Dobradiça 35mm', type: 'material', unit: 'un', unit_price: 5 },
    { name: 'Corrediça telescópica', type: 'material', unit: 'par', unit_price: 22 },
    { name: 'Puxador', type: 'material', unit: 'un', unit_price: 11 },
    { name: 'Parafusos', type: 'material', unit: 'kit', unit_price: 14 },
    { name: 'Fundo duro 3mm', type: 'material', unit: 'm²', unit_price: 18 },
    { name: 'Mão de obra hora', type: 'service', unit: 'h', unit_price: 62 },
    { name: 'Montagem projeto', type: 'service', unit: 'un', unit_price: 295 },
    { name: 'Instalação', type: 'service', unit: 'h', unit_price: 67 },
  ],
};
