import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";

const layoutPath = resolve(__dirname, "../../app/layout.tsx");
let layoutContent: string;

beforeEach(() => {
  layoutContent = readFileSync(layoutPath, "utf-8");
});

describe("app/layout.tsx — Fonte Manrope e Metadados Root", () => {
  describe("Fonte Manrope", () => {
    it("importa Manrope de next/font/google (não Geist)", () => {
      expect(layoutContent).toContain("Manrope");
      expect(layoutContent).toContain("next/font/google");
    });

    it("não importa Geist nem Geist_Mono", () => {
      expect(layoutContent).not.toContain("Geist_Mono");
      // Verifica que não há import da fonte Geist (pode conter a palavra em outros contextos)
      expect(layoutContent).not.toMatch(/import.*Geist.*from/);
    });

    it("configura a variável CSS --font-manrope", () => {
      expect(layoutContent).toContain('variable: "--font-manrope"');
    });

    it("inclui subsets: ['latin']", () => {
      expect(layoutContent).toContain('subsets: ["latin"]');
    });

    it("configura display: 'swap'", () => {
      expect(layoutContent).toContain('display: "swap"');
    });

    it("aplica a variável da fonte no elemento html", () => {
      expect(layoutContent).toContain("manrope.variable");
    });
  });

  describe("Metadados root", () => {
    it("metadata.title contém 'Orça Fácil'", () => {
      expect(layoutContent).toContain("Orça Fácil");
    });

    it("metadata.title contém o subtítulo completo da marca", () => {
      expect(layoutContent).toContain(
        "Orça Fácil — Orçamentos de Móveis Planejados para Marceneiros"
      );
    });

    it("metadata.title não é o valor padrão do Next.js", () => {
      expect(layoutContent).not.toContain("Create Next App");
    });

    it("metadata.description não é a string padrão do Next.js", () => {
      expect(layoutContent).not.toContain(
        "Generated by create next app"
      );
    });

    it("metadata.description descreve o produto real", () => {
      expect(layoutContent).toContain("marceneiros");
    });

    it("configura metadata.robots com index e follow", () => {
      expect(layoutContent).toContain("robots");
      expect(layoutContent).toContain("index: true");
      expect(layoutContent).toContain("follow: true");
    });
  });

  describe("Atributo lang do elemento html", () => {
    it("elemento <html> tem lang='pt-BR'", () => {
      expect(layoutContent).toContain('lang="pt-BR"');
    });

    it("não tem lang='en'", () => {
      expect(layoutContent).not.toContain('lang="en"');
    });
  });

  describe("Ícones preservados (task_03)", () => {
    it("preserva metadata.icons com favicon.svg", () => {
      expect(layoutContent).toContain("favicon.svg");
    });

    it("preserva metadata.icons com apple-touch-icon.png", () => {
      expect(layoutContent).toContain("apple-touch-icon.png");
    });
  });
});
